<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kabupatens=[
            [ 'id_kab' =>'1101', 'nama_kab' => 'Kabupaten Simeulue', 'id_prov' => '11'],
[ 'id_kab' =>'1102', 'nama_kab' => 'Kabupaten Aceh Singkil', 'id_prov' => '11'],
[ 'id_kab' =>'1103', 'nama_kab' => 'Kabupaten Aceh Selatan', 'id_prov' => '11'],
[ 'id_kab' =>'1104', 'nama_kab' => 'Kabupaten Aceh Tenggara', 'id_prov' => '11'],
[ 'id_kab' =>'1105', 'nama_kab' => 'Kabupaten Aceh Timur', 'id_prov' => '11'],
[ 'id_kab' =>'1106', 'nama_kab' => 'Kabupaten Aceh Tengah', 'id_prov' => '11'],
[ 'id_kab' =>'1107', 'nama_kab' => 'Kabupaten Aceh Barat', 'id_prov' => '11'],
[ 'id_kab' =>'1108', 'nama_kab' => 'Kabupaten Aceh Besar', 'id_prov' => '11'],
[ 'id_kab' =>'1109', 'nama_kab' => 'Kabupaten Pidie', 'id_prov' => '11'],
[ 'id_kab' =>'1110', 'nama_kab' => 'Kabupaten Bireuen', 'id_prov' => '11'],
[ 'id_kab' =>'1111', 'nama_kab' => 'Kabupaten Aceh Utara', 'id_prov' => '11'],
[ 'id_kab' =>'1112', 'nama_kab' => 'Kabupaten Aceh Barat Daya', 'id_prov' => '11'],
[ 'id_kab' =>'1113', 'nama_kab' => 'Kabupaten Gayo Lues', 'id_prov' => '11'],
[ 'id_kab' =>'1114', 'nama_kab' => 'Kabupaten Aceh Tamiang', 'id_prov' => '11'],
[ 'id_kab' =>'1115', 'nama_kab' => 'Kabupaten Nagan Raya', 'id_prov' => '11'],
[ 'id_kab' =>'1116', 'nama_kab' => 'Kabupaten Aceh Jaya', 'id_prov' => '11'],
[ 'id_kab' =>'1117', 'nama_kab' => 'Kabupaten Bener Meriah', 'id_prov' => '11'],
[ 'id_kab' =>'1118', 'nama_kab' => 'Kabupaten Pidie Jaya', 'id_prov' => '11'],
[ 'id_kab' =>'1171', 'nama_kab' => 'Kota Banda Aceh', 'id_prov' => '11'],
[ 'id_kab' =>'1172', 'nama_kab' => 'Kota Sabang', 'id_prov' => '11'],
[ 'id_kab' =>'1173', 'nama_kab' => 'Kota Langsa', 'id_prov' => '11'],
[ 'id_kab' =>'1174', 'nama_kab' => 'Kota Lhokseumawe', 'id_prov' => '11'],
[ 'id_kab' =>'1175', 'nama_kab' => 'Kota Subulussalam', 'id_prov' => '11'],
[ 'id_kab' =>'1201', 'nama_kab' => 'Kabupaten Nias', 'id_prov' => '12'],
[ 'id_kab' =>'1202', 'nama_kab' => 'Kabupaten Mandailing Natal', 'id_prov' => '12'],
[ 'id_kab' =>'1203', 'nama_kab' => 'Kabupaten Tapanuli Selatan', 'id_prov' => '12'],
[ 'id_kab' =>'1204', 'nama_kab' => 'Kabupaten Tapanuli Tengah', 'id_prov' => '12'],
[ 'id_kab' =>'1205', 'nama_kab' => 'Kabupaten Tapanuli Utara', 'id_prov' => '12'],
[ 'id_kab' =>'1206', 'nama_kab' => 'Kabupaten Toba Samosir', 'id_prov' => '12'],
[ 'id_kab' =>'1207', 'nama_kab' => 'Kabupaten Labuhan Batu', 'id_prov' => '12'],
[ 'id_kab' =>'1208', 'nama_kab' => 'Kabupaten Asahan', 'id_prov' => '12'],
[ 'id_kab' =>'1209', 'nama_kab' => 'Kabupaten Simalungun', 'id_prov' => '12'],
[ 'id_kab' =>'1210', 'nama_kab' => 'Kabupaten Dairi', 'id_prov' => '12'],
[ 'id_kab' =>'1211', 'nama_kab' => 'Kabupaten Karo', 'id_prov' => '12'],
[ 'id_kab' =>'1212', 'nama_kab' => 'Kabupaten Deli Serdang', 'id_prov' => '12'],
[ 'id_kab' =>'1213', 'nama_kab' => 'Kabupaten Langkat', 'id_prov' => '12'],
[ 'id_kab' =>'1214', 'nama_kab' => 'Kabupaten Nias Selatan', 'id_prov' => '12'],
[ 'id_kab' =>'1215', 'nama_kab' => 'Kabupaten Humbang Hasundutan', 'id_prov' => '12'],
[ 'id_kab' =>'1216', 'nama_kab' => 'Kabupaten Pakpak Bharat', 'id_prov' => '12'],
[ 'id_kab' =>'1217', 'nama_kab' => 'Kabupaten Samosir', 'id_prov' => '12'],
[ 'id_kab' =>'1218', 'nama_kab' => 'Kabupaten Serdang Bedagai', 'id_prov' => '12'],
[ 'id_kab' =>'1219', 'nama_kab' => 'Kabupaten Batu Bara', 'id_prov' => '12'],
[ 'id_kab' =>'1220', 'nama_kab' => 'Kabupaten Padang Lawas Utara', 'id_prov' => '12'],
[ 'id_kab' =>'1221', 'nama_kab' => 'Kabupaten Padang Lawas', 'id_prov' => '12'],
[ 'id_kab' =>'1222', 'nama_kab' => 'Kabupaten Labuhan Batu Selatan', 'id_prov' => '12'],
[ 'id_kab' =>'1223', 'nama_kab' => 'Kabupaten Labuhan Batu Utara', 'id_prov' => '12'],
[ 'id_kab' =>'1224', 'nama_kab' => 'Kabupaten Nias Utara', 'id_prov' => '12'],
[ 'id_kab' =>'1225', 'nama_kab' => 'Kabupaten Nias Barat', 'id_prov' => '12'],
[ 'id_kab' =>'1271', 'nama_kab' => 'Kota Sibolga', 'id_prov' => '12'],
[ 'id_kab' =>'1272', 'nama_kab' => 'Kota Tanjung Balai', 'id_prov' => '12'],
[ 'id_kab' =>'1273', 'nama_kab' => 'Kota Pematang Siantar', 'id_prov' => '12'],
[ 'id_kab' =>'1274', 'nama_kab' => 'Kota Tebing Tinggi', 'id_prov' => '12'],
[ 'id_kab' =>'1275', 'nama_kab' => 'Kota Medan', 'id_prov' => '12'],
[ 'id_kab' =>'1276', 'nama_kab' => 'Kota Binjai', 'id_prov' => '12'],
[ 'id_kab' =>'1277', 'nama_kab' => 'Kota Padangsidimpuan', 'id_prov' => '12'],
[ 'id_kab' =>'1278', 'nama_kab' => 'Kota Gunungsitoli', 'id_prov' => '12'],
[ 'id_kab' =>'1301', 'nama_kab' => 'Kabupaten Kepulauan Mentawai', 'id_prov' => '13'],
[ 'id_kab' =>'1302', 'nama_kab' => 'Kabupaten Pesisir Selatan', 'id_prov' => '13'],
[ 'id_kab' =>'1303', 'nama_kab' => 'Kabupaten Solok', 'id_prov' => '13'],
[ 'id_kab' =>'1304', 'nama_kab' => 'Kabupaten Sijunjung', 'id_prov' => '13'],
[ 'id_kab' =>'1305', 'nama_kab' => 'Kabupaten Tanah Datar', 'id_prov' => '13'],
[ 'id_kab' =>'1306', 'nama_kab' => 'Kabupaten Padang Pariaman', 'id_prov' => '13'],
[ 'id_kab' =>'1307', 'nama_kab' => 'Kabupaten Agam', 'id_prov' => '13'],
[ 'id_kab' =>'1308', 'nama_kab' => 'Kabupaten Lima Puluh Kota', 'id_prov' => '13'],
[ 'id_kab' =>'1309', 'nama_kab' => 'Kabupaten Pasaman', 'id_prov' => '13'],
[ 'id_kab' =>'1310', 'nama_kab' => 'Kabupaten Solok Selatan', 'id_prov' => '13'],
[ 'id_kab' =>'1311', 'nama_kab' => 'Kabupaten Dharmasraya', 'id_prov' => '13'],
[ 'id_kab' =>'1312', 'nama_kab' => 'Kabupaten Pasaman Barat', 'id_prov' => '13'],
[ 'id_kab' =>'1371', 'nama_kab' => 'Kota Padang', 'id_prov' => '13'],
[ 'id_kab' =>'1372', 'nama_kab' => 'Kota Solok', 'id_prov' => '13'],
[ 'id_kab' =>'1373', 'nama_kab' => 'Kota Sawah Lunto', 'id_prov' => '13'],
[ 'id_kab' =>'1374', 'nama_kab' => 'Kota Padang Panjang', 'id_prov' => '13'],
[ 'id_kab' =>'1375', 'nama_kab' => 'Kota Bukittinggi', 'id_prov' => '13'],
[ 'id_kab' =>'1376', 'nama_kab' => 'Kota Payakumbuh', 'id_prov' => '13'],
[ 'id_kab' =>'1377', 'nama_kab' => 'Kota Pariaman', 'id_prov' => '13'],
[ 'id_kab' =>'1401', 'nama_kab' => 'Kabupaten Kuantan Singingi', 'id_prov' => '14'],
[ 'id_kab' =>'1402', 'nama_kab' => 'Kabupaten Indragiri Hulu', 'id_prov' => '14'],
[ 'id_kab' =>'1403', 'nama_kab' => 'Kabupaten Indragiri Hilir', 'id_prov' => '14'],
[ 'id_kab' =>'1404', 'nama_kab' => 'Kabupaten Pelalawan', 'id_prov' => '14'],
[ 'id_kab' =>'1405', 'nama_kab' => 'Kabupaten S I A K', 'id_prov' => '14'],
[ 'id_kab' =>'1406', 'nama_kab' => 'Kabupaten Kampar', 'id_prov' => '14'],
[ 'id_kab' =>'1407', 'nama_kab' => 'Kabupaten Rokan Hulu', 'id_prov' => '14'],
[ 'id_kab' =>'1408', 'nama_kab' => 'Kabupaten Bengkalis', 'id_prov' => '14'],
[ 'id_kab' =>'1409', 'nama_kab' => 'Kabupaten Rokan Hilir', 'id_prov' => '14'],
[ 'id_kab' =>'1410', 'nama_kab' => 'Kabupaten Kepulauan Meranti', 'id_prov' => '14'],
[ 'id_kab' =>'1471', 'nama_kab' => 'Kota Pekanbaru', 'id_prov' => '14'],
[ 'id_kab' =>'1473', 'nama_kab' => 'Kota D U M A I', 'id_prov' => '14'],
[ 'id_kab' =>'1501', 'nama_kab' => 'Kabupaten Kerinci', 'id_prov' => '15'],
[ 'id_kab' =>'1502', 'nama_kab' => 'Kabupaten Merangin', 'id_prov' => '15'],
[ 'id_kab' =>'1503', 'nama_kab' => 'Kabupaten Sarolangun', 'id_prov' => '15'],
[ 'id_kab' =>'1504', 'nama_kab' => 'Kabupaten Batang Hari', 'id_prov' => '15'],
[ 'id_kab' =>'1505', 'nama_kab' => 'Kabupaten Muaro Jambi', 'id_prov' => '15'],
[ 'id_kab' =>'1506', 'nama_kab' => 'Kabupaten Tanjung Jabung Timur', 'id_prov' => '15'],
[ 'id_kab' =>'1507', 'nama_kab' => 'Kabupaten Tanjung Jabung Barat', 'id_prov' => '15'],
[ 'id_kab' =>'1508', 'nama_kab' => 'Kabupaten Tebo', 'id_prov' => '15'],
[ 'id_kab' =>'1509', 'nama_kab' => 'Kabupaten Bungo', 'id_prov' => '15'],
[ 'id_kab' =>'1571', 'nama_kab' => 'Kota Jambi', 'id_prov' => '15'],
[ 'id_kab' =>'1572', 'nama_kab' => 'Kota Sungai Penuh', 'id_prov' => '15'],
[ 'id_kab' =>'1601', 'nama_kab' => 'Kabupaten Ogan Komering Ulu', 'id_prov' => '16'],
[ 'id_kab' =>'1602', 'nama_kab' => 'Kabupaten Ogan Komering Ilir', 'id_prov' => '16'],
[ 'id_kab' =>'1603', 'nama_kab' => 'Kabupaten Muara Enim', 'id_prov' => '16'],
[ 'id_kab' =>'1604', 'nama_kab' => 'Kabupaten Lahat', 'id_prov' => '16'],
[ 'id_kab' =>'1605', 'nama_kab' => 'Kabupaten Musi Rawas', 'id_prov' => '16'],
[ 'id_kab' =>'1606', 'nama_kab' => 'Kabupaten Musi Banyuasin', 'id_prov' => '16'],
[ 'id_kab' =>'1607', 'nama_kab' => 'Kabupaten Banyu Asin', 'id_prov' => '16'],
[ 'id_kab' =>'1608', 'nama_kab' => 'Kabupaten Ogan Komering Ulu Selatan', 'id_prov' => '16'],
[ 'id_kab' =>'1609', 'nama_kab' => 'Kabupaten Ogan Komering Ulu Timur', 'id_prov' => '16'],
[ 'id_kab' =>'1610', 'nama_kab' => 'Kabupaten Ogan Ilir', 'id_prov' => '16'],
[ 'id_kab' =>'1611', 'nama_kab' => 'Kabupaten Empat Lawang', 'id_prov' => '16'],
[ 'id_kab' =>'1612', 'nama_kab' => 'Kabupaten Penukal Abab Lematang Ilir', 'id_prov' => '16'],
[ 'id_kab' =>'1613', 'nama_kab' => 'Kabupaten Musi Rawas Utara', 'id_prov' => '16'],
[ 'id_kab' =>'1671', 'nama_kab' => 'Kota Palembang', 'id_prov' => '16'],
[ 'id_kab' =>'1672', 'nama_kab' => 'Kota Prabumulih', 'id_prov' => '16'],
[ 'id_kab' =>'1673', 'nama_kab' => 'Kota Pagar Alam', 'id_prov' => '16'],
[ 'id_kab' =>'1674', 'nama_kab' => 'Kota Lubuklinggau', 'id_prov' => '16'],
[ 'id_kab' =>'1701', 'nama_kab' => 'Kabupaten Bengkulu Selatan', 'id_prov' => '17'],
[ 'id_kab' =>'1702', 'nama_kab' => 'Kabupaten Rejang Lebong', 'id_prov' => '17'],
[ 'id_kab' =>'1703', 'nama_kab' => 'Kabupaten Bengkulu Utara', 'id_prov' => '17'],
[ 'id_kab' =>'1704', 'nama_kab' => 'Kabupaten Kaur', 'id_prov' => '17'],
[ 'id_kab' =>'1705', 'nama_kab' => 'Kabupaten Seluma', 'id_prov' => '17'],
[ 'id_kab' =>'1706', 'nama_kab' => 'Kabupaten Mukomuko', 'id_prov' => '17'],
[ 'id_kab' =>'1707', 'nama_kab' => 'Kabupaten Lebong', 'id_prov' => '17'],
[ 'id_kab' =>'1708', 'nama_kab' => 'Kabupaten Kepahiang', 'id_prov' => '17'],
[ 'id_kab' =>'1709', 'nama_kab' => 'Kabupaten Bengkulu Tengah', 'id_prov' => '17'],
[ 'id_kab' =>'1771', 'nama_kab' => 'Kota Bengkulu', 'id_prov' => '17'],
[ 'id_kab' =>'1801', 'nama_kab' => 'Kabupaten Lampung Barat', 'id_prov' => '18'],
[ 'id_kab' =>'1802', 'nama_kab' => 'Kabupaten Tanggamus', 'id_prov' => '18'],
[ 'id_kab' =>'1803', 'nama_kab' => 'Kabupaten Lampung Selatan', 'id_prov' => '18'],
[ 'id_kab' =>'1804', 'nama_kab' => 'Kabupaten Lampung Timur', 'id_prov' => '18'],
[ 'id_kab' =>'1805', 'nama_kab' => 'Kabupaten Lampung Tengah', 'id_prov' => '18'],
[ 'id_kab' =>'1806', 'nama_kab' => 'Kabupaten Lampung Utara', 'id_prov' => '18'],
[ 'id_kab' =>'1807', 'nama_kab' => 'Kabupaten Way Kanan', 'id_prov' => '18'],
[ 'id_kab' =>'1808', 'nama_kab' => 'Kabupaten Tulangbawang', 'id_prov' => '18'],
[ 'id_kab' =>'1809', 'nama_kab' => 'Kabupaten Pesawaran', 'id_prov' => '18'],
[ 'id_kab' =>'1810', 'nama_kab' => 'Kabupaten Pringsewu', 'id_prov' => '18'],
[ 'id_kab' =>'1811', 'nama_kab' => 'Kabupaten Mesuji', 'id_prov' => '18'],
[ 'id_kab' =>'1812', 'nama_kab' => 'Kabupaten Tulang Bawang Barat', 'id_prov' => '18'],
[ 'id_kab' =>'1813', 'nama_kab' => 'Kabupaten Pesisir Barat', 'id_prov' => '18'],
[ 'id_kab' =>'1871', 'nama_kab' => 'Kota Bandar Lampung', 'id_prov' => '18'],
[ 'id_kab' =>'1872', 'nama_kab' => 'Kota Metro', 'id_prov' => '18'],
[ 'id_kab' =>'1901', 'nama_kab' => 'Kabupaten Bangka', 'id_prov' => '19'],
[ 'id_kab' =>'1902', 'nama_kab' => 'Kabupaten Belitung', 'id_prov' => '19'],
[ 'id_kab' =>'1903', 'nama_kab' => 'Kabupaten Bangka Barat', 'id_prov' => '19'],
[ 'id_kab' =>'1904', 'nama_kab' => 'Kabupaten Bangka Tengah', 'id_prov' => '19'],
[ 'id_kab' =>'1905', 'nama_kab' => 'Kabupaten Bangka Selatan', 'id_prov' => '19'],
[ 'id_kab' =>'1906', 'nama_kab' => 'Kabupaten Belitung Timur', 'id_prov' => '19'],
[ 'id_kab' =>'1971', 'nama_kab' => 'Kota Pangkalpinang', 'id_prov' => '19'],
[ 'id_kab' =>'2101', 'nama_kab' => 'Kabupaten Karimun', 'id_prov' => '21'],
[ 'id_kab' =>'2102', 'nama_kab' => 'Kabupaten Bintan', 'id_prov' => '21'],
[ 'id_kab' =>'2103', 'nama_kab' => 'Kabupaten Natuna', 'id_prov' => '21'],
[ 'id_kab' =>'2104', 'nama_kab' => 'Kabupaten Lingga', 'id_prov' => '21'],
[ 'id_kab' =>'2105', 'nama_kab' => 'Kabupaten Kepulauan Anambas', 'id_prov' => '21'],
[ 'id_kab' =>'2171', 'nama_kab' => 'Kota B A T A M', 'id_prov' => '21'],
[ 'id_kab' =>'2172', 'nama_kab' => 'Kota Tanjung Pinang', 'id_prov' => '21'],
[ 'id_kab' =>'3101', 'nama_kab' => 'Kabupaten Kepulauan Seribu', 'id_prov' => '31'],
[ 'id_kab' =>'3171', 'nama_kab' => 'Kota Jakarta Selatan', 'id_prov' => '31'],
[ 'id_kab' =>'3172', 'nama_kab' => 'Kota Jakarta Timur', 'id_prov' => '31'],
[ 'id_kab' =>'3173', 'nama_kab' => 'Kota Jakarta Pusat', 'id_prov' => '31'],
[ 'id_kab' =>'3174', 'nama_kab' => 'Kota Jakarta Barat', 'id_prov' => '31'],
[ 'id_kab' =>'3175', 'nama_kab' => 'Kota Jakarta Utara', 'id_prov' => '31'],
[ 'id_kab' =>'3201', 'nama_kab' => 'Kabupaten Bogor', 'id_prov' => '32'],
[ 'id_kab' =>'3202', 'nama_kab' => 'Kabupaten Sukabumi', 'id_prov' => '32'],
[ 'id_kab' =>'3203', 'nama_kab' => 'Kabupaten Cianjur', 'id_prov' => '32'],
[ 'id_kab' =>'3204', 'nama_kab' => 'Kabupaten Bandung', 'id_prov' => '32'],
[ 'id_kab' =>'3205', 'nama_kab' => 'Kabupaten Garut', 'id_prov' => '32'],
[ 'id_kab' =>'3206', 'nama_kab' => 'Kabupaten Tasikmalaya', 'id_prov' => '32'],
[ 'id_kab' =>'3207', 'nama_kab' => 'Kabupaten Ciamis', 'id_prov' => '32'],
[ 'id_kab' =>'3208', 'nama_kab' => 'Kabupaten Kuningan', 'id_prov' => '32'],
[ 'id_kab' =>'3209', 'nama_kab' => 'Kabupaten Cirebon', 'id_prov' => '32'],
[ 'id_kab' =>'3210', 'nama_kab' => 'Kabupaten Majalengka', 'id_prov' => '32'],
[ 'id_kab' =>'3211', 'nama_kab' => 'Kabupaten Sumedang', 'id_prov' => '32'],
[ 'id_kab' =>'3212', 'nama_kab' => 'Kabupaten Indramayu', 'id_prov' => '32'],
[ 'id_kab' =>'3213', 'nama_kab' => 'Kabupaten Subang', 'id_prov' => '32'],
[ 'id_kab' =>'3214', 'nama_kab' => 'Kabupaten Purwakarta', 'id_prov' => '32'],
[ 'id_kab' =>'3215', 'nama_kab' => 'Kabupaten Karawang', 'id_prov' => '32'],
[ 'id_kab' =>'3216', 'nama_kab' => 'Kabupaten Bekasi', 'id_prov' => '32'],
[ 'id_kab' =>'3217', 'nama_kab' => 'Kabupaten Bandung Barat', 'id_prov' => '32'],
[ 'id_kab' =>'3218', 'nama_kab' => 'Kabupaten Pangandaran', 'id_prov' => '32'],
[ 'id_kab' =>'3271', 'nama_kab' => 'Kota Bogor', 'id_prov' => '32'],
[ 'id_kab' =>'3272', 'nama_kab' => 'Kota Sukabumi', 'id_prov' => '32'],
[ 'id_kab' =>'3273', 'nama_kab' => 'Kota Bandung', 'id_prov' => '32'],
[ 'id_kab' =>'3274', 'nama_kab' => 'Kota Cirebon', 'id_prov' => '32'],
[ 'id_kab' =>'3275', 'nama_kab' => 'Kota Bekasi', 'id_prov' => '32'],
[ 'id_kab' =>'3276', 'nama_kab' => 'Kota Depok', 'id_prov' => '32'],
[ 'id_kab' =>'3277', 'nama_kab' => 'Kota Cimahi', 'id_prov' => '32'],
[ 'id_kab' =>'3278', 'nama_kab' => 'Kota Tasikmalaya', 'id_prov' => '32'],
[ 'id_kab' =>'3279', 'nama_kab' => 'Kota Banjar', 'id_prov' => '32'],
[ 'id_kab' =>'3301', 'nama_kab' => 'Kabupaten Cilacap', 'id_prov' => '33'],
[ 'id_kab' =>'3302', 'nama_kab' => 'Kabupaten Banyumas', 'id_prov' => '33'],
[ 'id_kab' =>'3303', 'nama_kab' => 'Kabupaten Purbalingga', 'id_prov' => '33'],
[ 'id_kab' =>'3304', 'nama_kab' => 'Kabupaten Banjarnegara', 'id_prov' => '33'],
[ 'id_kab' =>'3305', 'nama_kab' => 'Kabupaten Kebumen', 'id_prov' => '33'],
[ 'id_kab' =>'3306', 'nama_kab' => 'Kabupaten Purworejo', 'id_prov' => '33'],
[ 'id_kab' =>'3307', 'nama_kab' => 'Kabupaten Wonosobo', 'id_prov' => '33'],
[ 'id_kab' =>'3308', 'nama_kab' => 'Kabupaten Magelang', 'id_prov' => '33'],
[ 'id_kab' =>'3309', 'nama_kab' => 'Kabupaten Boyolali', 'id_prov' => '33'],
[ 'id_kab' =>'3310', 'nama_kab' => 'Kabupaten Klaten', 'id_prov' => '33'],
[ 'id_kab' =>'3311', 'nama_kab' => 'Kabupaten Sukoharjo', 'id_prov' => '33'],
[ 'id_kab' =>'3312', 'nama_kab' => 'Kabupaten Wonogiri', 'id_prov' => '33'],
[ 'id_kab' =>'3313', 'nama_kab' => 'Kabupaten Karanganyar', 'id_prov' => '33'],
[ 'id_kab' =>'3314', 'nama_kab' => 'Kabupaten Sragen', 'id_prov' => '33'],
[ 'id_kab' =>'3315', 'nama_kab' => 'Kabupaten Grobogan', 'id_prov' => '33'],
[ 'id_kab' =>'3316', 'nama_kab' => 'Kabupaten Blora', 'id_prov' => '33'],
[ 'id_kab' =>'3317', 'nama_kab' => 'Kabupaten Rembang', 'id_prov' => '33'],
[ 'id_kab' =>'3318', 'nama_kab' => 'Kabupaten Pati', 'id_prov' => '33'],
[ 'id_kab' =>'3319', 'nama_kab' => 'Kabupaten Kudus', 'id_prov' => '33'],
[ 'id_kab' =>'3320', 'nama_kab' => 'Kabupaten Jepara', 'id_prov' => '33'],
[ 'id_kab' =>'3321', 'nama_kab' => 'Kabupaten Demak', 'id_prov' => '33'],
[ 'id_kab' =>'3322', 'nama_kab' => 'Kabupaten Semarang', 'id_prov' => '33'],
[ 'id_kab' =>'3323', 'nama_kab' => 'Kabupaten Temanggung', 'id_prov' => '33'],
[ 'id_kab' =>'3324', 'nama_kab' => 'Kabupaten Kendal', 'id_prov' => '33'],
[ 'id_kab' =>'3325', 'nama_kab' => 'Kabupaten Batang', 'id_prov' => '33'],
[ 'id_kab' =>'3326', 'nama_kab' => 'Kabupaten Pekalongan', 'id_prov' => '33'],
[ 'id_kab' =>'3327', 'nama_kab' => 'Kabupaten Pemalang', 'id_prov' => '33'],
[ 'id_kab' =>'3328', 'nama_kab' => 'Kabupaten Tegal', 'id_prov' => '33'],
[ 'id_kab' =>'3329', 'nama_kab' => 'Kabupaten Brebes', 'id_prov' => '33'],
[ 'id_kab' =>'3371', 'nama_kab' => 'Kota Magelang', 'id_prov' => '33'],
[ 'id_kab' =>'3372', 'nama_kab' => 'Kota Surakarta', 'id_prov' => '33'],
[ 'id_kab' =>'3373', 'nama_kab' => 'Kota Salatiga', 'id_prov' => '33'],
[ 'id_kab' =>'3374', 'nama_kab' => 'Kota Semarang', 'id_prov' => '33'],
[ 'id_kab' =>'3375', 'nama_kab' => 'Kota Pekalongan', 'id_prov' => '33'],
[ 'id_kab' =>'3376', 'nama_kab' => 'Kota Tegal', 'id_prov' => '33'],
[ 'id_kab' =>'3401', 'nama_kab' => 'Kabupaten Kulon Progo', 'id_prov' => '34'],
[ 'id_kab' =>'3402', 'nama_kab' => 'Kabupaten Bantul', 'id_prov' => '34'],
[ 'id_kab' =>'3403', 'nama_kab' => 'Kabupaten Gunungkidul', 'id_prov' => '34'],
[ 'id_kab' =>'3404', 'nama_kab' => 'Kabupaten Sleman', 'id_prov' => '34'],
[ 'id_kab' =>'3471', 'nama_kab' => 'Kota Yogyakarta', 'id_prov' => '34'],
[ 'id_kab' =>'3501', 'nama_kab' => 'Kabupaten Pacitan', 'id_prov' => '35'],
[ 'id_kab' =>'3502', 'nama_kab' => 'Kabupaten Ponorogo', 'id_prov' => '35'],
[ 'id_kab' =>'3503', 'nama_kab' => 'Kabupaten Trenggalek', 'id_prov' => '35'],
[ 'id_kab' =>'3504', 'nama_kab' => 'Kabupaten Tulungagung', 'id_prov' => '35'],
[ 'id_kab' =>'3505', 'nama_kab' => 'Kabupaten Blitar', 'id_prov' => '35'],
[ 'id_kab' =>'3506', 'nama_kab' => 'Kabupaten Kediri', 'id_prov' => '35'],
[ 'id_kab' =>'3507', 'nama_kab' => 'Kabupaten Malang', 'id_prov' => '35'],
[ 'id_kab' =>'3508', 'nama_kab' => 'Kabupaten Lumajang', 'id_prov' => '35'],
[ 'id_kab' =>'3509', 'nama_kab' => 'Kabupaten Jember', 'id_prov' => '35'],
[ 'id_kab' =>'3510', 'nama_kab' => 'Kabupaten Banyuwangi', 'id_prov' => '35'],
[ 'id_kab' =>'3511', 'nama_kab' => 'Kabupaten Bondowoso', 'id_prov' => '35'],
[ 'id_kab' =>'3512', 'nama_kab' => 'Kabupaten Situbondo', 'id_prov' => '35'],
[ 'id_kab' =>'3513', 'nama_kab' => 'Kabupaten Probolinggo', 'id_prov' => '35'],
[ 'id_kab' =>'3514', 'nama_kab' => 'Kabupaten Pasuruan', 'id_prov' => '35'],
[ 'id_kab' =>'3515', 'nama_kab' => 'Kabupaten Sidoarjo', 'id_prov' => '35'],
[ 'id_kab' =>'3516', 'nama_kab' => 'Kabupaten Mojokerto', 'id_prov' => '35'],
[ 'id_kab' =>'3517', 'nama_kab' => 'Kabupaten Jombang', 'id_prov' => '35'],
[ 'id_kab' =>'3518', 'nama_kab' => 'Kabupaten Nganjuk', 'id_prov' => '35'],
[ 'id_kab' =>'3519', 'nama_kab' => 'Kabupaten Madiun', 'id_prov' => '35'],
[ 'id_kab' =>'3520', 'nama_kab' => 'Kabupaten Magetan', 'id_prov' => '35'],
[ 'id_kab' =>'3521', 'nama_kab' => 'Kabupaten Ngawi', 'id_prov' => '35'],
[ 'id_kab' =>'3522', 'nama_kab' => 'Kabupaten Bojonegoro', 'id_prov' => '35'],
[ 'id_kab' =>'3523', 'nama_kab' => 'Kabupaten Tuban', 'id_prov' => '35'],
[ 'id_kab' =>'3524', 'nama_kab' => 'Kabupaten Lamongan', 'id_prov' => '35'],
[ 'id_kab' =>'3525', 'nama_kab' => 'Kabupaten Gresik', 'id_prov' => '35'],
[ 'id_kab' =>'3526', 'nama_kab' => 'Kabupaten Bangkalan', 'id_prov' => '35'],
[ 'id_kab' =>'3527', 'nama_kab' => 'Kabupaten Sampang', 'id_prov' => '35'],
[ 'id_kab' =>'3528', 'nama_kab' => 'Kabupaten Pamekasan', 'id_prov' => '35'],
[ 'id_kab' =>'3529', 'nama_kab' => 'Kabupaten Sumenep', 'id_prov' => '35'],
[ 'id_kab' =>'3571', 'nama_kab' => 'Kota Kediri', 'id_prov' => '35'],
[ 'id_kab' =>'3572', 'nama_kab' => 'Kota Blitar', 'id_prov' => '35'],
[ 'id_kab' =>'3573', 'nama_kab' => 'Kota Malang', 'id_prov' => '35'],
[ 'id_kab' =>'3574', 'nama_kab' => 'Kota Probolinggo', 'id_prov' => '35'],
[ 'id_kab' =>'3575', 'nama_kab' => 'Kota Pasuruan', 'id_prov' => '35'],
[ 'id_kab' =>'3576', 'nama_kab' => 'Kota Mojokerto', 'id_prov' => '35'],
[ 'id_kab' =>'3577', 'nama_kab' => 'Kota Madiun', 'id_prov' => '35'],
[ 'id_kab' =>'3578', 'nama_kab' => 'Kota Surabaya', 'id_prov' => '35'],
[ 'id_kab' =>'3579', 'nama_kab' => 'Kota Batu', 'id_prov' => '35'],
[ 'id_kab' =>'3601', 'nama_kab' => 'Kabupaten Pandeglang', 'id_prov' => '36'],
[ 'id_kab' =>'3602', 'nama_kab' => 'Kabupaten Lebak', 'id_prov' => '36'],
[ 'id_kab' =>'3603', 'nama_kab' => 'Kabupaten Tangerang', 'id_prov' => '36'],
[ 'id_kab' =>'3604', 'nama_kab' => 'Kabupaten Serang', 'id_prov' => '36'],
[ 'id_kab' =>'3671', 'nama_kab' => 'Kota Tangerang', 'id_prov' => '36'],
[ 'id_kab' =>'3672', 'nama_kab' => 'Kota Cilegon', 'id_prov' => '36'],
[ 'id_kab' =>'3673', 'nama_kab' => 'Kota Serang', 'id_prov' => '36'],
[ 'id_kab' =>'3674', 'nama_kab' => 'Kota Tangerang Selatan', 'id_prov' => '36'],
[ 'id_kab' =>'5101', 'nama_kab' => 'Kabupaten Jembrana', 'id_prov' => '51'],
[ 'id_kab' =>'5102', 'nama_kab' => 'Kabupaten Tabanan', 'id_prov' => '51'],
[ 'id_kab' =>'5103', 'nama_kab' => 'Kabupaten Badung', 'id_prov' => '51'],
[ 'id_kab' =>'5104', 'nama_kab' => 'Kabupaten Gianyar', 'id_prov' => '51'],
[ 'id_kab' =>'5105', 'nama_kab' => 'Kabupaten Klungkung', 'id_prov' => '51'],
[ 'id_kab' =>'5106', 'nama_kab' => 'Kabupaten Bangli', 'id_prov' => '51'],
[ 'id_kab' =>'5107', 'nama_kab' => 'Kabupaten Karangasem', 'id_prov' => '51'],
[ 'id_kab' =>'5108', 'nama_kab' => 'Kabupaten Buleleng', 'id_prov' => '51'],
[ 'id_kab' =>'5171', 'nama_kab' => 'Kota Denpasar', 'id_prov' => '51'],
[ 'id_kab' =>'5201', 'nama_kab' => 'Kabupaten Lombok Barat', 'id_prov' => '52'],
[ 'id_kab' =>'5202', 'nama_kab' => 'Kabupaten Lombok Tengah', 'id_prov' => '52'],
[ 'id_kab' =>'5203', 'nama_kab' => 'Kabupaten Lombok Timur', 'id_prov' => '52'],
[ 'id_kab' =>'5204', 'nama_kab' => 'Kabupaten Sumbawa', 'id_prov' => '52'],
[ 'id_kab' =>'5205', 'nama_kab' => 'Kabupaten Dompu', 'id_prov' => '52'],
[ 'id_kab' =>'5206', 'nama_kab' => 'Kabupaten Bima', 'id_prov' => '52'],
[ 'id_kab' =>'5207', 'nama_kab' => 'Kabupaten Sumbawa Barat', 'id_prov' => '52'],
[ 'id_kab' =>'5208', 'nama_kab' => 'Kabupaten Lombok Utara', 'id_prov' => '52'],
[ 'id_kab' =>'5271', 'nama_kab' => 'Kota Mataram', 'id_prov' => '52'],
[ 'id_kab' =>'5272', 'nama_kab' => 'Kota Bima', 'id_prov' => '52'],
[ 'id_kab' =>'5301', 'nama_kab' => 'Kabupaten Sumba Barat', 'id_prov' => '53'],
[ 'id_kab' =>'5302', 'nama_kab' => 'Kabupaten Sumba Timur', 'id_prov' => '53'],
[ 'id_kab' =>'5303', 'nama_kab' => 'Kabupaten Kupang', 'id_prov' => '53'],
[ 'id_kab' =>'5304', 'nama_kab' => 'Kabupaten Timor Tengah Selatan', 'id_prov' => '53'],
[ 'id_kab' =>'5305', 'nama_kab' => 'Kabupaten Timor Tengah Utara', 'id_prov' => '53'],
[ 'id_kab' =>'5306', 'nama_kab' => 'Kabupaten Belu', 'id_prov' => '53'],
[ 'id_kab' =>'5307', 'nama_kab' => 'Kabupaten Alor', 'id_prov' => '53'],
[ 'id_kab' =>'5308', 'nama_kab' => 'Kabupaten Lembata', 'id_prov' => '53'],
[ 'id_kab' =>'5309', 'nama_kab' => 'Kabupaten Flores Timur', 'id_prov' => '53'],
[ 'id_kab' =>'5310', 'nama_kab' => 'Kabupaten Sikka', 'id_prov' => '53'],
[ 'id_kab' =>'5311', 'nama_kab' => 'Kabupaten Ende', 'id_prov' => '53'],
[ 'id_kab' =>'5312', 'nama_kab' => 'Kabupaten Ngada', 'id_prov' => '53'],
[ 'id_kab' =>'5313', 'nama_kab' => 'Kabupaten Manggarai', 'id_prov' => '53'],
[ 'id_kab' =>'5314', 'nama_kab' => 'Kabupaten Rote Ndao', 'id_prov' => '53'],
[ 'id_kab' =>'5315', 'nama_kab' => 'Kabupaten Manggarai Barat', 'id_prov' => '53'],
[ 'id_kab' =>'5316', 'nama_kab' => 'Kabupaten Sumba Tengah', 'id_prov' => '53'],
[ 'id_kab' =>'5317', 'nama_kab' => 'Kabupaten Sumba Barat Daya', 'id_prov' => '53'],
[ 'id_kab' =>'5318', 'nama_kab' => 'Kabupaten Nagekeo', 'id_prov' => '53'],
[ 'id_kab' =>'5319', 'nama_kab' => 'Kabupaten Manggarai Timur', 'id_prov' => '53'],
[ 'id_kab' =>'5320', 'nama_kab' => 'Kabupaten Sabu Raijua', 'id_prov' => '53'],
[ 'id_kab' =>'5321', 'nama_kab' => 'Kabupaten Malaka', 'id_prov' => '53'],
[ 'id_kab' =>'5371', 'nama_kab' => 'Kota Kupang', 'id_prov' => '53'],
[ 'id_kab' =>'6101', 'nama_kab' => 'Kabupaten Sambas', 'id_prov' => '61'],
[ 'id_kab' =>'6102', 'nama_kab' => 'Kabupaten Bengkayang', 'id_prov' => '61'],
[ 'id_kab' =>'6103', 'nama_kab' => 'Kabupaten Landak', 'id_prov' => '61'],
[ 'id_kab' =>'6104', 'nama_kab' => 'Kabupaten Mempawah', 'id_prov' => '61'],
[ 'id_kab' =>'6105', 'nama_kab' => 'Kabupaten Sanggau', 'id_prov' => '61'],
[ 'id_kab' =>'6106', 'nama_kab' => 'Kabupaten Ketapang', 'id_prov' => '61'],
[ 'id_kab' =>'6107', 'nama_kab' => 'Kabupaten Sintang', 'id_prov' => '61'],
[ 'id_kab' =>'6108', 'nama_kab' => 'Kabupaten Kapuas Hulu', 'id_prov' => '61'],
[ 'id_kab' =>'6109', 'nama_kab' => 'Kabupaten Sekadau', 'id_prov' => '61'],
[ 'id_kab' =>'6110', 'nama_kab' => 'Kabupaten Melawi', 'id_prov' => '61'],
[ 'id_kab' =>'6111', 'nama_kab' => 'Kabupaten Kayong Utara', 'id_prov' => '61'],
[ 'id_kab' =>'6112', 'nama_kab' => 'Kabupaten Kubu Raya', 'id_prov' => '61'],
[ 'id_kab' =>'6171', 'nama_kab' => 'Kota Pontianak', 'id_prov' => '61'],
[ 'id_kab' =>'6172', 'nama_kab' => 'Kota Singkawang', 'id_prov' => '61'],
[ 'id_kab' =>'6201', 'nama_kab' => 'Kabupaten Kotawaringin Barat', 'id_prov' => '62'],
[ 'id_kab' =>'6202', 'nama_kab' => 'Kabupaten Kotawaringin Timur', 'id_prov' => '62'],
[ 'id_kab' =>'6203', 'nama_kab' => 'Kabupaten Kapuas', 'id_prov' => '62'],
[ 'id_kab' =>'6204', 'nama_kab' => 'Kabupaten Barito Selatan', 'id_prov' => '62'],
[ 'id_kab' =>'6205', 'nama_kab' => 'Kabupaten Barito Utara', 'id_prov' => '62'],
[ 'id_kab' =>'6206', 'nama_kab' => 'Kabupaten Sukamara', 'id_prov' => '62'],
[ 'id_kab' =>'6207', 'nama_kab' => 'Kabupaten Lamandau', 'id_prov' => '62'],
[ 'id_kab' =>'6208', 'nama_kab' => 'Kabupaten Seruyan', 'id_prov' => '62'],
[ 'id_kab' =>'6209', 'nama_kab' => 'Kabupaten Katingan', 'id_prov' => '62'],
[ 'id_kab' =>'6210', 'nama_kab' => 'Kabupaten Pulang Pisau', 'id_prov' => '62'],
[ 'id_kab' =>'6211', 'nama_kab' => 'Kabupaten Gunung Mas', 'id_prov' => '62'],
[ 'id_kab' =>'6212', 'nama_kab' => 'Kabupaten Barito Timur', 'id_prov' => '62'],
[ 'id_kab' =>'6213', 'nama_kab' => 'Kabupaten Murung Raya', 'id_prov' => '62'],
[ 'id_kab' =>'6271', 'nama_kab' => 'Kota Palangka Raya', 'id_prov' => '62'],
[ 'id_kab' =>'6301', 'nama_kab' => 'Kabupaten Tanah Laut', 'id_prov' => '63'],
[ 'id_kab' =>'6302', 'nama_kab' => 'Kabupaten Kotabaru', 'id_prov' => '63'],
[ 'id_kab' =>'6303', 'nama_kab' => 'Kabupaten Banjar', 'id_prov' => '63'],
[ 'id_kab' =>'6304', 'nama_kab' => 'Kabupaten Barito Kuala', 'id_prov' => '63'],
[ 'id_kab' =>'6305', 'nama_kab' => 'Kabupaten Tapin', 'id_prov' => '63'],
[ 'id_kab' =>'6306', 'nama_kab' => 'Kabupaten Hulu Sungai Selatan', 'id_prov' => '63'],
[ 'id_kab' =>'6307', 'nama_kab' => 'Kabupaten Hulu Sungai Tengah', 'id_prov' => '63'],
[ 'id_kab' =>'6308', 'nama_kab' => 'Kabupaten Hulu Sungai Utara', 'id_prov' => '63'],
[ 'id_kab' =>'6309', 'nama_kab' => 'Kabupaten Tabalong', 'id_prov' => '63'],
[ 'id_kab' =>'6310', 'nama_kab' => 'Kabupaten Tanah Bumbu', 'id_prov' => '63'],
[ 'id_kab' =>'6311', 'nama_kab' => 'Kabupaten Balangan', 'id_prov' => '63'],
[ 'id_kab' =>'6371', 'nama_kab' => 'Kota Banjarmasin', 'id_prov' => '63'],
[ 'id_kab' =>'6372', 'nama_kab' => 'Kota Banjar Baru', 'id_prov' => '63'],
[ 'id_kab' =>'6401', 'nama_kab' => 'Kabupaten Paser', 'id_prov' => '64'],
[ 'id_kab' =>'6402', 'nama_kab' => 'Kabupaten Kutai Barat', 'id_prov' => '64'],
[ 'id_kab' =>'6403', 'nama_kab' => 'Kabupaten Kutai Kartanegara', 'id_prov' => '64'],
[ 'id_kab' =>'6404', 'nama_kab' => 'Kabupaten Kutai Timur', 'id_prov' => '64'],
[ 'id_kab' =>'6405', 'nama_kab' => 'Kabupaten Berau', 'id_prov' => '64'],
[ 'id_kab' =>'6409', 'nama_kab' => 'Kabupaten Penajam Paser Utara', 'id_prov' => '64'],
[ 'id_kab' =>'6411', 'nama_kab' => 'Kabupaten Mahakam Hulu', 'id_prov' => '64'],
[ 'id_kab' =>'6471', 'nama_kab' => 'Kota Balikpapan', 'id_prov' => '64'],
[ 'id_kab' =>'6472', 'nama_kab' => 'Kota Samarinda', 'id_prov' => '64'],
[ 'id_kab' =>'6474', 'nama_kab' => 'Kota Bontang', 'id_prov' => '64'],
[ 'id_kab' =>'6501', 'nama_kab' => 'Kabupaten Malinau', 'id_prov' => '65'],
[ 'id_kab' =>'6502', 'nama_kab' => 'Kabupaten Bulungan', 'id_prov' => '65'],
[ 'id_kab' =>'6503', 'nama_kab' => 'Kabupaten Tana Tidung', 'id_prov' => '65'],
[ 'id_kab' =>'6504', 'nama_kab' => 'Kabupaten Nunukan', 'id_prov' => '65'],
[ 'id_kab' =>'6571', 'nama_kab' => 'Kota Tarakan', 'id_prov' => '65'],
[ 'id_kab' =>'7101', 'nama_kab' => 'Kabupaten Bolaang Mongondow', 'id_prov' => '71'],
[ 'id_kab' =>'7102', 'nama_kab' => 'Kabupaten Minahasa', 'id_prov' => '71'],
[ 'id_kab' =>'7103', 'nama_kab' => 'Kabupaten Kepulauan Sangihe', 'id_prov' => '71'],
[ 'id_kab' =>'7104', 'nama_kab' => 'Kabupaten Kepulauan Talaud', 'id_prov' => '71'],
[ 'id_kab' =>'7105', 'nama_kab' => 'Kabupaten Minahasa Selatan', 'id_prov' => '71'],
[ 'id_kab' =>'7106', 'nama_kab' => 'Kabupaten Minahasa Utara', 'id_prov' => '71'],
[ 'id_kab' =>'7107', 'nama_kab' => 'Kabupaten Bolaang Mongondow Utara', 'id_prov' => '71'],
[ 'id_kab' =>'7108', 'nama_kab' => 'Kabupaten Siau Tagulandang Biaro', 'id_prov' => '71'],
[ 'id_kab' =>'7109', 'nama_kab' => 'Kabupaten Minahasa Tenggara', 'id_prov' => '71'],
[ 'id_kab' =>'7110', 'nama_kab' => 'Kabupaten Bolaang Mongondow Selatan', 'id_prov' => '71'],
[ 'id_kab' =>'7111', 'nama_kab' => 'Kabupaten Bolaang Mongondow Timur', 'id_prov' => '71'],
[ 'id_kab' =>'7171', 'nama_kab' => 'Kota Manado', 'id_prov' => '71'],
[ 'id_kab' =>'7172', 'nama_kab' => 'Kota Bitung', 'id_prov' => '71'],
[ 'id_kab' =>'7173', 'nama_kab' => 'Kota Tomohon', 'id_prov' => '71'],
[ 'id_kab' =>'7174', 'nama_kab' => 'Kota Kotamobagu', 'id_prov' => '71'],
[ 'id_kab' =>'7201', 'nama_kab' => 'Kabupaten Banggai Kepulauan', 'id_prov' => '72'],
[ 'id_kab' =>'7202', 'nama_kab' => 'Kabupaten Banggai', 'id_prov' => '72'],
[ 'id_kab' =>'7203', 'nama_kab' => 'Kabupaten Morowali', 'id_prov' => '72'],
[ 'id_kab' =>'7204', 'nama_kab' => 'Kabupaten Poso', 'id_prov' => '72'],
[ 'id_kab' =>'7205', 'nama_kab' => 'Kabupaten Donggala', 'id_prov' => '72'],
[ 'id_kab' =>'7206', 'nama_kab' => 'Kabupaten Toli-toli', 'id_prov' => '72'],
[ 'id_kab' =>'7207', 'nama_kab' => 'Kabupaten Buol', 'id_prov' => '72'],
[ 'id_kab' =>'7208', 'nama_kab' => 'Kabupaten Parigi Moutong', 'id_prov' => '72'],
[ 'id_kab' =>'7209', 'nama_kab' => 'Kabupaten Tojo Una-una', 'id_prov' => '72'],
[ 'id_kab' =>'7210', 'nama_kab' => 'Kabupaten Sigi', 'id_prov' => '72'],
[ 'id_kab' =>'7211', 'nama_kab' => 'Kabupaten Banggai Laut', 'id_prov' => '72'],
[ 'id_kab' =>'7212', 'nama_kab' => 'Kabupaten Morowali Utara', 'id_prov' => '72'],
[ 'id_kab' =>'7271', 'nama_kab' => 'Kota Palu', 'id_prov' => '72'],
[ 'id_kab' =>'7301', 'nama_kab' => 'Kabupaten Kepulauan Selayar', 'id_prov' => '73'],
[ 'id_kab' =>'7302', 'nama_kab' => 'Kabupaten Bulukumba', 'id_prov' => '73'],
[ 'id_kab' =>'7303', 'nama_kab' => 'Kabupaten Bantaeng', 'id_prov' => '73'],
[ 'id_kab' =>'7304', 'nama_kab' => 'Kabupaten Jeneponto', 'id_prov' => '73'],
[ 'id_kab' =>'7305', 'nama_kab' => 'Kabupaten Takalar', 'id_prov' => '73'],
[ 'id_kab' =>'7306', 'nama_kab' => 'Kabupaten Gowa', 'id_prov' => '73'],
[ 'id_kab' =>'7307', 'nama_kab' => 'Kabupaten Sinjai', 'id_prov' => '73'],
[ 'id_kab' =>'7308', 'nama_kab' => 'Kabupaten Maros', 'id_prov' => '73'],
[ 'id_kab' =>'7309', 'nama_kab' => 'Kabupaten Pangkajene Dan Kepulauan', 'id_prov' => '73'],
[ 'id_kab' =>'7310', 'nama_kab' => 'Kabupaten Barru', 'id_prov' => '73'],
[ 'id_kab' =>'7311', 'nama_kab' => 'Kabupaten Bone', 'id_prov' => '73'],
[ 'id_kab' =>'7312', 'nama_kab' => 'Kabupaten Soppeng', 'id_prov' => '73'],
[ 'id_kab' =>'7313', 'nama_kab' => 'Kabupaten Wajo', 'id_prov' => '73'],
[ 'id_kab' =>'7314', 'nama_kab' => 'Kabupaten Sidenreng Rappang', 'id_prov' => '73'],
[ 'id_kab' =>'7315', 'nama_kab' => 'Kabupaten Pinrang', 'id_prov' => '73'],
[ 'id_kab' =>'7316', 'nama_kab' => 'Kabupaten Enrekang', 'id_prov' => '73'],
[ 'id_kab' =>'7317', 'nama_kab' => 'Kabupaten Luwu', 'id_prov' => '73'],
[ 'id_kab' =>'7318', 'nama_kab' => 'Kabupaten Tana Toraja', 'id_prov' => '73'],
[ 'id_kab' =>'7322', 'nama_kab' => 'Kabupaten Luwu Utara', 'id_prov' => '73'],
[ 'id_kab' =>'7325', 'nama_kab' => 'Kabupaten Luwu Timur', 'id_prov' => '73'],
[ 'id_kab' =>'7326', 'nama_kab' => 'Kabupaten Toraja Utara', 'id_prov' => '73'],
[ 'id_kab' =>'7371', 'nama_kab' => 'Kota Makassar', 'id_prov' => '73'],
[ 'id_kab' =>'7372', 'nama_kab' => 'Kota Parepare', 'id_prov' => '73'],
[ 'id_kab' =>'7373', 'nama_kab' => 'Kota Palopo', 'id_prov' => '73'],
[ 'id_kab' =>'7401', 'nama_kab' => 'Kabupaten Buton', 'id_prov' => '74'],
[ 'id_kab' =>'7402', 'nama_kab' => 'Kabupaten Muna', 'id_prov' => '74'],
[ 'id_kab' =>'7403', 'nama_kab' => 'Kabupaten Konawe', 'id_prov' => '74'],
[ 'id_kab' =>'7404', 'nama_kab' => 'Kabupaten Kolaka', 'id_prov' => '74'],
[ 'id_kab' =>'7405', 'nama_kab' => 'Kabupaten Konawe Selatan', 'id_prov' => '74'],
[ 'id_kab' =>'7406', 'nama_kab' => 'Kabupaten Bombana', 'id_prov' => '74'],
[ 'id_kab' =>'7407', 'nama_kab' => 'Kabupaten Wakatobi', 'id_prov' => '74'],
[ 'id_kab' =>'7408', 'nama_kab' => 'Kabupaten Kolaka Utara', 'id_prov' => '74'],
[ 'id_kab' =>'7409', 'nama_kab' => 'Kabupaten Buton Utara', 'id_prov' => '74'],
[ 'id_kab' =>'7410', 'nama_kab' => 'Kabupaten Konawe Utara', 'id_prov' => '74'],
[ 'id_kab' =>'7411', 'nama_kab' => 'Kabupaten Kolaka Timur', 'id_prov' => '74'],
[ 'id_kab' =>'7412', 'nama_kab' => 'Kabupaten Konawe Kepulauan', 'id_prov' => '74'],
[ 'id_kab' =>'7413', 'nama_kab' => 'Kabupaten Muna Barat', 'id_prov' => '74'],
[ 'id_kab' =>'7414', 'nama_kab' => 'Kabupaten Buton Tengah', 'id_prov' => '74'],
[ 'id_kab' =>'7415', 'nama_kab' => 'Kabupaten Buton Selatan', 'id_prov' => '74'],
[ 'id_kab' =>'7471', 'nama_kab' => 'Kota Kendari', 'id_prov' => '74'],
[ 'id_kab' =>'7472', 'nama_kab' => 'Kota Baubau', 'id_prov' => '74'],
[ 'id_kab' =>'7501', 'nama_kab' => 'Kabupaten Boalemo', 'id_prov' => '75'],
[ 'id_kab' =>'7502', 'nama_kab' => 'Kabupaten Gorontalo', 'id_prov' => '75'],
[ 'id_kab' =>'7503', 'nama_kab' => 'Kabupaten Pohuwato', 'id_prov' => '75'],
[ 'id_kab' =>'7504', 'nama_kab' => 'Kabupaten Bone Bolango', 'id_prov' => '75'],
[ 'id_kab' =>'7505', 'nama_kab' => 'Kabupaten Gorontalo Utara', 'id_prov' => '75'],
[ 'id_kab' =>'7571', 'nama_kab' => 'Kota Gorontalo', 'id_prov' => '75'],
[ 'id_kab' =>'7601', 'nama_kab' => 'Kabupaten Majene', 'id_prov' => '76'],
[ 'id_kab' =>'7602', 'nama_kab' => 'Kabupaten Polewali Mandar', 'id_prov' => '76'],
[ 'id_kab' =>'7603', 'nama_kab' => 'Kabupaten Mamasa', 'id_prov' => '76'],
[ 'id_kab' =>'7604', 'nama_kab' => 'Kabupaten Mamuju', 'id_prov' => '76'],
[ 'id_kab' =>'7605', 'nama_kab' => 'Kabupaten Pasangkayu', 'id_prov' => '76'],
[ 'id_kab' =>'7606', 'nama_kab' => 'Kabupaten Mamuju Tengah', 'id_prov' => '76'],
[ 'id_kab' =>'8101', 'nama_kab' => 'Kabupaten Kepulauan Tanimbar', 'id_prov' => '81'],
[ 'id_kab' =>'8102', 'nama_kab' => 'Kabupaten Maluku Tenggara', 'id_prov' => '81'],
[ 'id_kab' =>'8103', 'nama_kab' => 'Kabupaten Maluku Tengah', 'id_prov' => '81'],
[ 'id_kab' =>'8104', 'nama_kab' => 'Kabupaten Buru', 'id_prov' => '81'],
[ 'id_kab' =>'8105', 'nama_kab' => 'Kabupaten Kepulauan Aru', 'id_prov' => '81'],
[ 'id_kab' =>'8106', 'nama_kab' => 'Kabupaten Seram Bagian Barat', 'id_prov' => '81'],
[ 'id_kab' =>'8107', 'nama_kab' => 'Kabupaten Seram Bagian Timur', 'id_prov' => '81'],
[ 'id_kab' =>'8108', 'nama_kab' => 'Kabupaten Maluku Barat Daya', 'id_prov' => '81'],
[ 'id_kab' =>'8109', 'nama_kab' => 'Kabupaten Buru Selatan', 'id_prov' => '81'],
[ 'id_kab' =>'8171', 'nama_kab' => 'Kota Ambon', 'id_prov' => '81'],
[ 'id_kab' =>'8172', 'nama_kab' => 'Kota Tual', 'id_prov' => '81'],
[ 'id_kab' =>'8201', 'nama_kab' => 'Kabupaten Halmahera Barat', 'id_prov' => '82'],
[ 'id_kab' =>'8202', 'nama_kab' => 'Kabupaten Halmahera Tengah', 'id_prov' => '82'],
[ 'id_kab' =>'8203', 'nama_kab' => 'Kabupaten Kepulauan Sula', 'id_prov' => '82'],
[ 'id_kab' =>'8204', 'nama_kab' => 'Kabupaten Halmahera Selatan', 'id_prov' => '82'],
[ 'id_kab' =>'8205', 'nama_kab' => 'Kabupaten Halmahera Utara', 'id_prov' => '82'],
[ 'id_kab' =>'8206', 'nama_kab' => 'Kabupaten Halmahera Timur', 'id_prov' => '82'],
[ 'id_kab' =>'8207', 'nama_kab' => 'Kabupaten Pulau Morotai', 'id_prov' => '82'],
[ 'id_kab' =>'8208', 'nama_kab' => 'Kabupaten Pulau Taliabu', 'id_prov' => '82'],
[ 'id_kab' =>'8271', 'nama_kab' => 'Kota Ternate', 'id_prov' => '82'],
[ 'id_kab' =>'8272', 'nama_kab' => 'Kota Tidore Kepulauan', 'id_prov' => '82'],
[ 'id_kab' =>'9101', 'nama_kab' => 'Kabupaten Fakfak', 'id_prov' => '91'],
[ 'id_kab' =>'9102', 'nama_kab' => 'Kabupaten Kaimana', 'id_prov' => '91'],
[ 'id_kab' =>'9103', 'nama_kab' => 'Kabupaten Teluk Wondama', 'id_prov' => '91'],
[ 'id_kab' =>'9104', 'nama_kab' => 'Kabupaten Teluk Bintuni', 'id_prov' => '91'],
[ 'id_kab' =>'9105', 'nama_kab' => 'Kabupaten Manokwari', 'id_prov' => '91'],
[ 'id_kab' =>'9106', 'nama_kab' => 'Kabupaten Sorong Selatan', 'id_prov' => '91'],
[ 'id_kab' =>'9107', 'nama_kab' => 'Kabupaten Sorong', 'id_prov' => '91'],
[ 'id_kab' =>'9108', 'nama_kab' => 'Kabupaten Raja Ampat', 'id_prov' => '91'],
[ 'id_kab' =>'9109', 'nama_kab' => 'Kabupaten Tambrauw', 'id_prov' => '91'],
[ 'id_kab' =>'9110', 'nama_kab' => 'Kabupaten Maybrat', 'id_prov' => '91'],
[ 'id_kab' =>'9111', 'nama_kab' => 'Kabupaten Manokwari Selatan', 'id_prov' => '91'],
[ 'id_kab' =>'9112', 'nama_kab' => 'Kabupaten Pegunungan Arfak', 'id_prov' => '91'],
[ 'id_kab' =>'9171', 'nama_kab' => 'Kota Sorong', 'id_prov' => '91'],
[ 'id_kab' =>'9401', 'nama_kab' => 'Kabupaten Merauke', 'id_prov' => '94'],
[ 'id_kab' =>'9402', 'nama_kab' => 'Kabupaten Jayawijaya', 'id_prov' => '94'],
[ 'id_kab' =>'9403', 'nama_kab' => 'Kabupaten Jayapura', 'id_prov' => '94'],
[ 'id_kab' =>'9404', 'nama_kab' => 'Kabupaten Nabire', 'id_prov' => '94'],
[ 'id_kab' =>'9408', 'nama_kab' => 'Kabupaten Kepulauan Yapen', 'id_prov' => '94'],
[ 'id_kab' =>'9409', 'nama_kab' => 'Kabupaten Biak Numfor', 'id_prov' => '94'],
[ 'id_kab' =>'9410', 'nama_kab' => 'Kabupaten Paniai', 'id_prov' => '94'],
[ 'id_kab' =>'9411', 'nama_kab' => 'Kabupaten Puncak Jaya', 'id_prov' => '94'],
[ 'id_kab' =>'9412', 'nama_kab' => 'Kabupaten Mimika', 'id_prov' => '94'],
[ 'id_kab' =>'9413', 'nama_kab' => 'Kabupaten Boven Digoel', 'id_prov' => '94'],
[ 'id_kab' =>'9414', 'nama_kab' => 'Kabupaten Mappi', 'id_prov' => '94'],
[ 'id_kab' =>'9415', 'nama_kab' => 'Kabupaten Asmat', 'id_prov' => '94'],
[ 'id_kab' =>'9416', 'nama_kab' => 'Kabupaten Yahukimo', 'id_prov' => '94'],
[ 'id_kab' =>'9417', 'nama_kab' => 'Kabupaten Pegunungan Bintang', 'id_prov' => '94'],
[ 'id_kab' =>'9418', 'nama_kab' => 'Kabupaten Tolikara', 'id_prov' => '94'],
[ 'id_kab' =>'9419', 'nama_kab' => 'Kabupaten Sarmi', 'id_prov' => '94'],
[ 'id_kab' =>'9420', 'nama_kab' => 'Kabupaten Keerom', 'id_prov' => '94'],
[ 'id_kab' =>'9426', 'nama_kab' => 'Kabupaten Waropen', 'id_prov' => '94'],
[ 'id_kab' =>'9427', 'nama_kab' => 'Kabupaten Supiori', 'id_prov' => '94'],
[ 'id_kab' =>'9428', 'nama_kab' => 'Kabupaten Mamberamo Raya', 'id_prov' => '94'],
[ 'id_kab' =>'9429', 'nama_kab' => 'Kabupaten Nduga', 'id_prov' => '94'],
[ 'id_kab' =>'9430', 'nama_kab' => 'Kabupaten Lanny Jaya', 'id_prov' => '94'],
[ 'id_kab' =>'9431', 'nama_kab' => 'Kabupaten Mamberamo Tengah', 'id_prov' => '94'],
[ 'id_kab' =>'9432', 'nama_kab' => 'Kabupaten Yalimo', 'id_prov' => '94'],
[ 'id_kab' =>'9433', 'nama_kab' => 'Kabupaten Puncak', 'id_prov' => '94'],
[ 'id_kab' =>'9434', 'nama_kab' => 'Kabupaten Dogiyai', 'id_prov' => '94'],
[ 'id_kab' =>'9435', 'nama_kab' => 'Kabupaten Intan Jaya', 'id_prov' => '94'],
[ 'id_kab' =>'9436', 'nama_kab' => 'Kabupaten Deiyai', 'id_prov' => '94'],
[ 'id_kab' =>'9471', 'nama_kab' => 'Kota Jayapura', 'id_prov' => '94'],

        ];

        for($i=0; $i<count($kabupatens);$i++){
            DB::table('kabupatens')->insert(
                [   'id_kab' => $kabupatens[$i]['id_kab'],
                    'nama_kab' => $kabupatens[$i]['nama_kab'],
                    'id_prov' => $kabupatens[$i]['id_prov']
                ]
            );
        }
    }
}
